name: CD-CI-Kurs
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
on: push
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Build with Maven
        
        run: |
          cd ./Lernjournal-Projekt-main/micronaut-datenbank
          mvn clean install

      - run: cd ./Lernjournal-Projekt-main/micronaut-datenbank
      - run: npm install -g bats
      - run: bats -v
